### ISSUE TITLE
Provide pre-compiled binaries

### ISSUE THREAD

**Issue by paulocoghi** [mamantoha/cryMPD#8]
Since Crystal is a compiled language, I would like to suggest to provide pre-compiled binaries.

This avoids:

- requiring the user to install Crystal first, just to be able to use cryMPD
- requiring the user to compile cryMPD

**Comment by mamantoha** [comment]
Closed via https://github.com/mamantoha/cryMPD/pull/9

**Comment by mamantoha** [comment]
Hi @paulocoghi . Please check https://github.com/mamantoha/cryMPD#binaries

**Comment by paulocoghi** [comment]
As soon as possible I will explain how you can publish the generated binaries as releases, to be available [here](https://github.com/mamantoha/cryMPD/releases)
